language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover


after_success:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
