language: php

matrix:
  include:
    - php: '7.1'
      env: OLDPHPUNIT=true
    - php: '7.2'
    - php: '7.3'
    - php: '7.4snapshot'


before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source --ignore-platform-reqs
  - if [ $OLDPHPUNIT == true ]; then composer require "phpunit/phpunit:6.5"; fi

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - bash <(curl -s https://codecov.io/bash)
